version: "3.7"
volumes:
  electrs_data:

services:
  electrs:
    container_name: electrs
    image: sr/electrs:latest
    build:
      context: ./electrs/
    restart: unless-stopped
    command:
      [
        "--timestamp",
        "--network=regtest",
        "--db-dir=/var/lib/electrs/db",
        "--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT}",
        "--daemon-p2p-addr=node1:${BITCOIN_PORT}",
        "--daemon-rpc-addr=node1:${BITCOIN_RPC_PORT}",
      ]
    volumes:
      - electrs_data:/home/electrs
    depends_on:
      - node1
    ports:
      - ${ELECTRS_PORT}:${ELECTRS_PORT}
    networks:
      lbnet:
        ipv4_address: 172.20.0.30
        aliases:
          - ${ELECTRS_HOST}
