version: "2.4"

volumes:
  lnp_data:
  rgb_data:

services:
  lnp1:
    container_name: ${COMPOSE_PROJECT_NAME}_lnp1
    image: stk-sr/lnp:${LNP_VERSION}-slim
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--port=${LNP_RPC_PORT}",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
      ]
    # ports:
    #   - "127.0.0.1:${LNP_PORT}:${LNP_PORT}"
    #   - "127.0.0.1:${LNP_RPC_PORT}:${LNP_RPC_PORT}"
    depends_on:
      - electrs
    volumes:
      - lnp_data:/var/lib/lnp/.lnp_node/
    networks:
      srnet:
        aliases:
          - ${LNP_HOST_1}

  lnp2:
    container_name: ${COMPOSE_PROJECT_NAME}_lnp2
    image: stk-sr/lnp:${LNP_VERSION}-slim
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--port=${LNP_RPC_PORT}",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
      ]
    # ports:
    #   - "127.0.0.1:${LNP_PORT}:${LNP_PORT}"
    #   - "127.0.0.1:${LNP_RPC_PORT}:${LNP_RPC_PORT}"
    depends_on:
      - electrs
    volumes:
      - lnp_data:/var/lib/lnp/.lnp_node/
    networks:
      srnet:
        aliases:
          - ${LNP_HOST_2}
