version: "2.4"
services:
  electrs:
    container_name: electrs
    image: sr/electrs:latest
    build:
      context: ./electrs/  
    restart: unless-stopped
    command:
      [
        "electrs",
        "--timestamp",
        "--network=regtest",
        "--db-dir=/home/electrs/db",
        "--electrum-rpc-addr=0.0.0.0:${ELECTRS_PORT}",
        "--daemon-p2p-addr=node1:${BITCOIN_PORT}",
        "--daemon-rpc-addr=node1:${BITCOIN_RPC_PORT}"
      ]
    depends_on:
      - node1
    networks:
      sr_network:
        aliases:
          - ${ELECTRS_HOST}
