version: "2.4"
services:
  lnp1:
    container_name: lnp1
    image: sr/lnp:latest
    build:
      context: ./lnp-node/
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
        "--data-dir=/var/lib/lnp"
      ]
    depends_on:
      - node1
      - electrs
    volumes:
      - lnp1_data:/var/lib/lnp
    expose: [9735, 62962]      
    networks:
      sr_network:
        ipv4_address: 172.20.0.8      
        aliases:
          - ${LNP_HOST_1}

  lnp2:
    container_name: lnp2
    image: sr/lnp:latest
    build:
      context: ./lnp-node/
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
        "--data-dir=/var/lib/lnp"
      ]
    depends_on:
      - node2
      - electrs
    volumes:
      - lnp2_data:/var/lib/lnp
    expose: [9735, 62962]
    networks:
      sr_network:
        ipv4_address: 172.20.0.10
        aliases:
          - ${LNP_HOST_2}

  cln1:
    container_name: cln1
    image: sr/cln:latest
    build:
      context: ./clightning/
    restart: unless-stopped
    command:
      [
        "--alias=${CLN_HOST_1}",
        "--network=regtest",
        "--large-channels",
        "--addr=0.0.0.0:${CLN_PORT}",
        "--bitcoin-cli=/opt/bitcoin/bin/bitcoin-cli",
        "--bitcoin-rpcconnect=${BITCOIN_HOST_1}",
        "--bitcoin-rpcport=${BITCOIN_RPC_PORT}",
        "--bitcoin-rpcuser=${BITCOIN_RPC_USER}",
        "--bitcoin-rpcpassword=${BITCOIN_RPC_PASSWORD}",
      ]
    depends_on:
      - node1
    networks:
      sr_network:
        ipv4_address: 172.20.0.12
        aliases:
          - ${CLN_HOST_1}
    volumes:
      - cln1_data:/root/.lightning
