version: "3.7"
volumes:
  cln1_data:
  cln2_data:
  lnd1_data:
  lnp1_data:
  lnp2_data:

services:
  lnp1:
    container_name: lnp1
    image: sr/lnp:latest
    build:
      context: ./lnp-node/
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
        "--msg=0.0.0.0:${LNP_MSG_PORT}",
        "--ctl=0.0.0.0:${LNP_CTL_PORT}",
        "--data-dir=/var/lib/lnp",
        "--threaded",
      ]
    depends_on:
      - electrs
    volumes:
      - lnp1_data:/var/lib/lnp
    expose: [9997, 9998, 9999, 9735, 62960, 62961, 62962]
    ports:
      - ${LNP_PORT}:${LNP_PORT}
      - ${LNP_MSG_PORT}:${LNP_MSG_PORT}
    networks:
      lbnet:
        ipv4_address: 172.20.0.8
        aliases:
          - ${LNP_HOST_1}

  lnp2:
    container_name: lnp2
    image: sr/lnp:latest
    build:
      context: ./lnp-node/
    restart: unless-stopped
    command:
      [
        "-vvvv",
        "--chain=regtest",
        "--electrum-port=${ELECTRS_PORT}",
        "--electrum-server=${ELECTRS_HOST}",
        "--msg=0.0.0.0:${LNP_MSG_PORT}",
        "--ctl=0.0.0.0:${LNP_CTL_PORT}",
        "--data-dir=/var/lib/lnp",
        "--threaded",
      ]
    depends_on:
      - electrs
    volumes:
      - lnp2_data:/var/lib/lnp
    expose: [9997, 9998, 9999, 9735, 62960, 62961, 62962]
    ports:
      - ${LNP_ALT_MSG_PORT}:${LNP_MSG_PORT}
    networks:
      lbnet:
        ipv4_address: 172.20.0.10
        aliases:
          - ${LNP_HOST_2}

  cln1:
    container_name: cln1
    image: sr/cln:latest
    build:
      context: ./clightning/
    restart: unless-stopped
    expose: [9735, 19735, 19846]
    command:
      [
        "--alias=${CLN_HOST_1}",
        "--network=regtest",
        "--large-channels",
        "--bitcoin-cli=/opt/bitcoin/bin/bitcoin-cli",
        "--bitcoin-rpcconnect=${BITCOIN_HOST_1}",
        "--bitcoin-rpcport=${BITCOIN_RPC_PORT}",
        "--bitcoin-rpcuser=${BITCOIN_RPC_USER}",
        "--bitcoin-rpcpassword=${BITCOIN_RPC_PASS}",
      ]
    depends_on:
      - node1
    networks:
      lbnet:
        ipv4_address: 172.20.0.12
        aliases:
          - ${CLN_HOST_1}
    volumes:
      - cln1_data:/root/.lightning

  cln2:
    container_name: cln2
    image: sr/cln:latest
    build:
      context: ./clightning/
    restart: unless-stopped
    expose: [9735, 19735, 19846]
    command:
      [
        "--alias=${CLN_HOST_2}",
        "--network=regtest",
        "--large-channels",
        "--bitcoin-cli=/opt/bitcoin/bin/bitcoin-cli",
        "--bitcoin-rpcconnect=${BITCOIN_HOST_1}",
        "--bitcoin-rpcport=${BITCOIN_RPC_PORT}",
        "--bitcoin-rpcuser=${BITCOIN_RPC_USER}",
        "--bitcoin-rpcpassword=${BITCOIN_RPC_PASS}",
      ]
    depends_on:
      - node1
    networks:
      lbnet:
        ipv4_address: 172.20.0.14
        aliases:
          - ${CLN_HOST_2}
    volumes:
      - cln2_data:/root/.lightning

  lnd1:
    container_name: lnd1
    image: sr/lnd1:latest
    build:
      context: ./lnd/
    restart: unless-stopped
    expose: [9735 10009]
    command:
      [
        "--debuglevel=debug",
        "--bitcoin.active",
        "--bitcoin.regtest",
        "--rpclisten=localhost:10009",
        "--rpclisten=${LND_HOST_1}:10009",
        "--bitcoin.node=bitcoind",
        "--bitcoind.rpchost=${BITCOIN_HOST_1}:${BITCOIN_RPC_PORT}",
        "--bitcoind.rpcuser=${BITCOIN_RPC_USER}",
        "--bitcoind.rpcpass=${BITCOIN_RPC_PASS}",
        "--bitcoind.zmqpubrawtx=tcp://${BITCOIN_HOST_1}:${BITCOIN_ZMQ_TX_PORT}",
        "--bitcoind.zmqpubrawblock=tcp://${BITCOIN_HOST_1}:${BITCOIN_ZMQ_BLOCK_PORT}",
      ]
    depends_on:
      - node1
    networks:
      lbnet:
        ipv4_address: 172.20.0.16
        aliases:
          - ${LND_HOST_1}
    volumes:
      - lnd1_data:/root/.lnd